# Generated by Django 3.1.2 on 2020-10-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_answer',
            field=models.IntegerField(default=0),
        ),
    ]
