# Generated by Django 3.1.2 on 2020-10-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201026_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=22, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.question'),
        ),
    ]
