# Generated by Django 3.1.3 on 2020-11-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201026_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('count_answer', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Расширенный пользователь',
                'verbose_name_plural': 'Расширенные пользователи',
            },
        ),
    ]
