# Generated by Django 3.1.3 on 2020-11-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_questionanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
